### ISSUE TITLE
Bare NCurses usage howto ?

### ISSUE THREAD

**Issue by asmodehn** [ronisbr/TextUserInterfaces.jl#12]
Hello, 

I am finding myself attempting to implement some terminal interactive (text-based) input in julia, and I finally found this **NCurses.jl wrapping**, that seems to work on my machine (tictactoe display something), unlike my first attempt at directly ccalling `Ncurses_jll` routines...

So I d like to know what would be the best way to get the very basic / lowlevel behavior of Ncurses in julia, without all the widgets added on top. something alike [python's curses](https://docs.python.org/3/library/curses.html)
Would splitting the NCurses in another repo/package wrapping make sense ?
Can I directly use NCurses from this package, but how ? Is there a tutorial/example somewhere ?

Thanks for the help. I have long experience in programming, but just getting my feet wet with Julia...
And thanks for the work on that ncurses wrapper, which could help me a lot !

**Comment by ronisbr** [comment]
Hi @asmodehn !

This package is under a huge rewrite. However, the submodule NCurses.jl is very stable.

You can do something like:

```julia
julia> using TextUserInterfaces

julia> using TextUserInterfaces.NCurses
```

And now you can call the NCurses functions that are registered. Take a look here:

https://github.com/ronisbr/TextUserInterfaces.jl/blob/master/src/submodules/NCurses/ncurses_functions.jl

**Comment by asmodehn** [comment]
In the package version I have (0.0.1) : 
```
julia> using TextUserInterfaces

julia> using TextUserInterfaces.NCurses
ERROR: UndefVarError: NCurses not defined

```

Also it seems `initscr()` is available from the lower module:
```
using TextUserInterfaces

stdscr = initscr()
```

gives me:
```
ERROR: LoadError: ArgumentError: NULL library handle
Stacktrace:
 [1] #dlsym#1
   @ ./libdl.jl:57 [inlined]
 [2] dlsym
   @ ./libdl.jl:56 [inlined]
 [3] initscr()
   @ TextUserInterfaces ~/.julia/packages/TextUserInterfaces/k1unl/src/ncurses/ncurses_functions.jl:132
 [4] top-level scope
   @ /opt/Projects/kittyforth/tui.jl:9

```
Which breings me to [`@eval $f($(argsj...)) = @_ccalln $f($(argsc...))::$r`](https://github.com/ronisbr/TextUserInterfaces.jl/blob/v0.0.1/src/ncurses/ncurses_functions.jl#L132) which is not really helpful...

Any clue ?

**Comment by ronisbr** [comment]
You need to use the development version! Type:

```julia
julia>]dev TerminalUserInterfaces
```

**Comment by asmodehn** [comment]
I didn't have much luck with that either:
```
(kittyforth) pkg> dev TerminalUserInterfaces
     Cloning git-repo `https://github.com/kdheepak/TerminalUserInterfaces.jl.git`

signal (11): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7fb1493ff008)
Allocations: 5726597 (Pool: 5722308; Big: 4289); GC: 7
Segmentation fault (core dumped)

```
or
```
(kittyforth) pkg> dev TextUserInterfaces
     Cloning git-repo `https://github.com/ronisbr/TextUserInterfaces.jl.git`

signal (11): Segmentation fault
in expression starting at none:0
unknown function (ip: 0x7ff776dff008)
Allocations: 4890650 (Pool: 4886749; Big: 3901); GC: 6
Segmentation fault (core dumped)
```

I m thinking it might be because of the `main` <-> `master` branch naming...
So I did a manual clone in the *proper place* (need to be careful with that `.jl` suffix).
Then I found out how to use a the dev version of a package from a script.

So now I am back to:
tui.jl
```
import Pkg
Pkg.develop("TextUserInterfaces")

using TextUserInterfaces
using TextUserInterfaces.NCurses

stdscr = initscr()
```
```
julia --project tui.jl
   Resolving package versions...
  No Changes to `/opt/Projects/kittyforth/Project.toml`
  No Changes to `/opt/Projects/kittyforth/Manifest.toml`
ERROR: LoadError: ArgumentError: NULL library handle
Stacktrace:
 [1] #dlsym#1
   @ ./libdl.jl:57 [inlined]
 [2] dlsym
   @ ./libdl.jl:56 [inlined]
 [3] initscr()
   @ TextUserInterfaces.NCurses ~/.julia/dev/TextUserInterfaces/src/submodules/NCurses/ncurses_functions.jl:328
 [4] top-level scope
   @ /opt/Projects/kittyforth/tui.jl:8
in expression starting at /opt/Projects/kittyforth/tui.jl:8

```

Looking at init_tui, I guess I miss a call to Lib.dlopen, I ll try to figure it out...
I just wish using NCurses.jl would be easier for beginners.

Let me know if I can help in any way.

**Comment by asmodehn** [comment]
Ok This works for me now, (with a caveat on the default git branch used by the repo maybe ?)
```
import Pkg
Pkg.develop("TextUserInterfaces")

using TextUserInterfaces
using TextUserInterfaces.NCurses

load_ncurses()
stdscr = initscr()
clear()
printw("Hello World !")
refresh()
getch()
endwin()
```
I'll start from there, thanks for all the help.
If you ever want to extract NCurses in its own package, ping me and I ll give you a hand.

Cheers !

**Comment by ronisbr** [comment]
I am glad it worked! You're welcome!

**Comment by ronisbr** [comment]
This is a package under heavy development. I am lacking time however to finish everything. That's why I did not tag a new version.
