### ISSUE TITLE
Unicode Plots

### ISSUE THREAD

**Issue by mdpetters** [ronisbr/TextUserInterfaces.jl#15]
Hi Ronan,

I am exploring the possibility to build embedded data acquisition systems that run as TUI app inside a tmux session that is accessible/usable via a low-bandwidth ssh connection. It seems that TextUserInterfaces.jl might be the way to start. I was just playing around with the examples in your repo and was exploring possible hooks to add plots. I came across an old post of yours on [Julia discourse](https://discourse.julialang.org/t/approaching-first-usable-release-of-textuserinterfaces-jl/50971) that shows that you made UnicodePlots.jl work. It looks fantastic! If you still have that code, would it be possible to share it as a snippet via a response? I am specifically wondering about how you "convert ANSI escaping color codes to Ncurses", and more generally how to take the Unicode Plots output and dump it onto a box. I would try to mash it into a reactive concept app that - assuming I succeed - could be added to the examples folder.

Markus

**Comment by ronisbr** [comment]
Hi @mdpetters !

Thanks!

TextUserInterfaces.jl is going through a major rewrite. I am almost done, but my time to do so is very limited unfortunately :( Hence, the interfaces changed a lot and the old code does not work here. However, if you want to convert ANSI escape sequences to NCurses colors, you only need to use a widget that I call ANSI label. It performs the correction automatically (however, there might be some edge cases).

To display a plot created by UnicodePlots.jl, you need to do:

```julia
using UnicodePlots
using TextUserInterfaces

function tui()
    initialize_tui()

    w = create_window(
        border = true,
        title  = " UnicodePlot.jl ",
    )

    c = w.widget_container

    ansi_label = @tui_ansi_label(
        parent        = c,
        text          = "",
        bottom_anchor = (:parent, :bottom),
        left_anchor   = (:parent, :left),
        right_anchor  = (:parent, :right),
        top_anchor    = (:parent, :top),
    )

    # Create a plot with UnicodePlots.jl.
    x = 0:0.01:10
    y = sin.(x)
    io = IOBuffer()
    show(
        IOContext(io, :color => true),
        lineplot(x, y; xlabel = "t", ylabel = "sin(t)")
    )
    str = String(take!(io))
    
    change_text!(ansi_label, str)

    app_main_loop()
end

tui()
```

This code creates a window that spans the entire terminal, adds a ANSI label that spans the entire window container, and adds the unicode plot there. Notice that you must use the development version of TextUserInterfaces.jl.

<img width="768" alt="Captura de Tela 2024-04-22 às 09 22 10" src="https://github.com/ronisbr/TextUserInterfaces.jl/assets/1068295/f0d5e0ab-57b6-42af-983b-898be1ee697e">

**Comment by ronisbr** [comment]
By the way, hit F1 to exit the main loop :)
