### ISSUE TITLE
Problems running examples in Julia 1.3

### ISSUE THREAD

**Issue by affans** [ronisbr/TextUserInterfaces.jl#6]
Running the `windows_and_widgets`
``` 
ERROR: LoadError: UndefVarError: @connect_signal not defined
in expression starting at REPL[4]:45
```
Running the tic tac toe example
```
julia> using TextUserInterfaces.NCurses
ERROR: UndefVarError: NCurses not defined
```

Version info:
```
julia> versioninfo()
Julia Version 1.3.1
Commit 2d5741174c (2019-12-30 21:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, broadwell)
```

**Comment by affans** [comment]
Actually, seems like the registered version is `v0.0.1` which is about 104 commits behind master. Upgrading to master to fix all the problem. Maybe it's time to tag a new release?

**Comment by ronisbr** [comment]
Hi @affans ,

There is still a long way to go until a stable version with the API I want. This package should be considered stable only if you want to use NCurses directly. In this case, it should be working pretty good. However, I do not want to tag a new release until I finish the API design and documentation. The goal is to have a package that provides an easier way to build TUIs than using NCurses directly.

If you want to try the examples for now, you will need to use the development version. Notice that I would really appreciate help to build the API and test the code. However, there are no docs. Thus, you will need to see the code if you want to take this path :)
