### ISSUE TITLE
WidgetCommon not defined?

### ISSUE THREAD

**Issue by leios** [ronisbr/TextUserInterfaces.jl#7]
Hello, I was poking around the examples and noticed that the tictactoe example did not seem to work on my machine and provided the following error.

```
ERROR: LoadError: UndefVarError: WidgetCommon not defined
Stacktrace:
 [1] top-level scope at /home/leios/.julia/packages/Parameters/CVyBv/src/Parameters.jl:572
 [2] top-level scope at REPL[1]:1
in expression starting at /home/leios/projects/TextUserInterfaces.jl/examples/tictactoe.jl:28
```

I found WidgetCommon being exported in [src/types/widgets.jl](https://github.com/ronisbr/TextUserInterfaces.jl/blob/master/src/types/widgets.jl), but the definition does not seem to be in that file.

**Comment by affans** [comment]
How did you add the package? The package is under development, so I would suggest adding the master branch. Something like `] add TextUserInterfaces#master`

See related issue: https://github.com/ronisbr/TextUserInterfaces.jl/issues/6

**Comment by ronisbr** [comment]
Yes! @affans is completely right! However, I am doing a major change to improve the loading time. I might have forgotten to update Tic Tac Toe. I will try to push the changes today or tomorrow, and then everything will be working again. Sorry about that :)

**Comment by leios** [comment]
I did
```
Pkg> add TextUserInterfaces#master
```
So it should be the master branch

**Comment by ronisbr** [comment]
So, I really forgot to update this example to use the new interface. I will try to fix this until tomorrow.

**Comment by leios** [comment]
Cool, thanks! No real rush, just poking around a bit. I should hopefully be using the package for some *somewhat* complicated stuff in the next few weeks, but we'll see.

Thanks for the active development!

**Comment by ronisbr** [comment]
Yes! It is in active development. It just turns out to be extremely complicated to create a API for TUIs. If you want to use NCURSES directly, then it is more or less good to go.

**Comment by leios** [comment]
Right now, ncurses is fine, what else would you be considering adding? Sorry, I don't see a project open or anything

**Comment by ronisbr** [comment]
I want to create an Julia-like API. So, instead of drawing things on screen (lines, text, etc.), I would like to provide widgets, focus manager, anchoring system to place the widgets, etc. More or less what we have when developing a Qt software (but waaaaaaaaay more simplified :D)

**Comment by ronisbr** [comment]
Done! Should be working now :)

**Comment by ronisbr** [comment]
Just one information, I have update many things internally. Now we have some useful signals and a new widget called Canvas. Hence, the custom widget in tic tac toe example is no longer needed. You will see that the code is much cleaner now.
