### ISSUE TITLE
initscr: NULL library handle

### ISSUE THREAD

**Issue by leios** [ronisbr/TextUserInterfaces.jl#8]
when running `initscr()` in the REPL or in a file, I get the following error
```
ERROR: ArgumentError: NULL library handle
Stacktrace:
 [1] #dlsym#1 at /build/julia/src/julia-1.4.2/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:54 [inlined]
 [2] dlsym at /build/julia/src/julia-1.4.2/usr/share/julia/stdlib/v1.4/Libdl/src/Libdl.jl:54 [inlined]
 [3] initscr() at /home/leios/.julia/packages/TextUserInterfaces/rwWM2/src/submodules/NCurses/ncurses_functions.jl:122
 [4] top-level scope at REPL[2]:1
```

Not sure where to start debugging this, but happy to help. I am simply looking for an ncurses interface in Julia (like the one for python)[https://docs.python.org/3/howto/curses.html]). I don't mind trying to use the TextUserInterface package, but I couldn't quite figure it out for my purposes.

As a note: I would love to help develop the NCurses portion of this library to bring it up-to-speed with the python implementation.

I am using the default ncurses package from the arch repos.

I also noticed that my ncurses library can be run by C(++) and python, but is not listed in the `dllist()` function. Is it supposed to be there? How do I get it there?

EDIT: Essentially, I am looking for something like the python `addstr()` and `movestr()` functionality right now. Could this be done with a canvas widget?

**Comment by ronisbr** [comment]
Hum that’s strange. Did you run the function `init_tui()`? It is suppose to load the libraries.

Btw, thanks for the help!! We will need all the workforce we can get to finish this package :)

**Comment by ronisbr** [comment]
Can you explain me what those functions do? The it seems that it can be replicated by the Label widget.

**Comment by leios** [comment]
The `init_tui()` seemed to work, so we can close this issue

As to the other question... Imagine a simple snake game. This requires moving a string around a window and changing it's size. Right now, it's unclear to me how I would do this with TextUserInterfaces without relying on NCurses.

The workflow for ncurses is usually:

1. Add characters (or strings) to a window
2. Move those characters or strings within the window and erase previous positions

For the snake game, this works pretty well. We just have an array of characters and locations and say `addch()` to each character  at each location in the array, then refresh the screen (deleting old, unused characters).

This workflow is kinda difficult to replicate in the widget interface. Right now, the only ways I have found to move a widget is by:

1. Creating a specific window for that widget and moving the window.
2. Creating an ANSI widget, then delete and recreate it each timestep with a new opc.

I assume there is also a move_widget function in the works?

If there is a snake that is dynamically changing in size, how would I represent that with widgets? Because I couldn't figure out how to move widgets, I would need to create a separate window for each element in the array and move the windows every step. This feels way less intuitive to me than just adding strings to a window.

As a final note, it seems that the windows created by TextUserInterfaces and NCurses are incompatible. Is there any plan to fix that (or am I just too noob to figure out how to get them to work together)?

**Comment by ronisbr** [comment]
I think that for a snake game you can easily use Canvas. It is just a 2 dimensional matrix that you specified a character and color to be drawn at each location. Thus, you track the dynamics offline and then copy to the matrix.

**Comment by leios** [comment]
Ok, I'll try to use that. Thanks for the help!
